# Generated by Django 5.0 on 2024-02-22 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0002_remove_users_place'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('Busoperators', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Manager.busoperator')),
            ],
        ),
        migrations.CreateModel(
            name='Buses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='images')),
                ('price', models.PositiveIntegerField()),
                ('description', models.CharField(max_length=500)),
                ('borading_point', models.CharField(max_length=500)),
                ('borading_time', models.TimeField()),
                ('Droping_point', models.CharField(max_length=500)),
                ('Droping_time', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('Operator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Manager.busoperator')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Manager.category')),
            ],
        ),
    ]
