# Generated by Django 5.0 on 2024-02-22 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0003_category_buses'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField()),
                ('start_date', models.DateTimeField()),
                ('due_date', models.DateTimeField()),
                ('offer_status', models.CharField(choices=[('active', 'active'), ('expired', 'expired')], default='active', max_length=200)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer_price', to='Manager.buses')),
                ('busoperators', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Manager.busoperator')),
            ],
        ),
    ]
