# Generated by Django 5.0 on 2024-02-22 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0004_offer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buses',
            old_name='Droping_point',
            new_name='boarding_point',
        ),
        migrations.RenameField(
            model_name='buses',
            old_name='Droping_time',
            new_name='boarding_time',
        ),
        migrations.RenameField(
            model_name='buses',
            old_name='borading_point',
            new_name='dropping_point',
        ),
        migrations.RenameField(
            model_name='buses',
            old_name='borading_time',
            new_name='dropping_time',
        ),
        migrations.AddField(
            model_name='buses',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
