# Generated by Django 5.0 on 2024-02-28 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0005_rename_droping_point_buses_boarding_point_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='buses',
            name='capacity',
            field=models.IntegerField(null=True),
        ),
    ]
