# Generated by Django 5.0.1 on 2024-02-28 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0007_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.CharField(max_length=50)),
                ('journey_date', models.DateField()),
                ('is_confirmed', models.BooleanField(default=False)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Manager.buses')),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Manager.users')),
            ],
            options={
                'unique_together': {('bus', 'journey_date', 'seat_number')},
            },
        ),
    ]
