# Generated by Django 5.0.1 on 2024-02-28 19:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0008_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='booking_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed')], default='Pending', max_length=100),
        ),
        migrations.AddField(
            model_name='reservation',
            name='reservation_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
