# Generated by Django 5.0.1 on 2024-02-28 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0009_reservation_booking_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='booking_status',
            new_name='reservation_status',
        ),
    ]
