# Generated by Django 5.0.1 on 2024-02-28 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0010_rename_booking_status_reservation_reservation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buses',
            name='price',
            field=models.IntegerField(),
        ),
    ]
