# Generated by Django 5.0.1 on 2024-02-28 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0011_alter_buses_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='passenger',
            new_name='user',
        ),
    ]
