# Generated by Django 5.0.2 on 2024-03-01 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0013_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='bio',
        ),
    ]
